from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('verify_phone/', views.verify_phone, name='verify_phone'),
    path('signup/', views.signup, name='signup'),
    # path('verify_email/<str:token>/', views.verify_email, name='verify_email'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    # path('verify_reset_token/<str:token>/', views.verify_reset_token, name='verify_reset_token'),
    # path('reset_password/', views.reset_password, name='reset_password'),
    path('driversignup/', views.driversignup, name='driversignup'),
    path('get_user_notifications/<str:user_id>/', views.get_user_notifications, name='get_user_notifications'),
    path('nearby_vehicles/<str:lat>/<str:lng>/', views.nearby_vehicles, name='nearby_vehicles'),
    path('create_ride_and_payment/', views.create_ride_and_payment, name='create_ride_and_payment'),
    path('create_rating/', views.create_rating, name='create_rating'),
    path('get_user_ratings/<int:user_id>/', views.get_user_ratings, name='get_user_ratings'),
    path('get_all_payments/', views.get_all_payments, name='get_all_payments'),
    path('get_driver_payments/<int:driver_id>/', views.get_driver_payments, name='get_driver_payments'),
    path('get_requested_rides/<int:user_id>/', views.get_requested_rides, name='get_requested_rides'),
    path('update_ride_status/', views.update_ride_status, name='update_ride_status'),
    path('send_expo_token/<int:user_id>/<str:expo_token>/', views.send_expo_token, name='send_expo_token'),
    path('notify_driver/', views.notify_driver, name='notify_driver'),
    path('get_driver_total_earnings/<int:user_id>/', views.get_driver_total_earnings, name='get_driver_total_earnings'),
    path('get_vincab_earnings/', views.get_vincab_earnings, name='get_vincab_earnings'),
    path('calculate_fare/<str:pickup_lat>/<str:pickup_lng>/<str:drop_lat>/<str:drop_lng>/', views.calculate_fare, name='calculate_fare'),
    path('get_ride_details/<int:rider_id>/', views.get_ride_details, name='get_ride_details'),

    # path('lipa_na_mpesa/<str:phone_number>/<str:amount>/', views.lipa_na_mpesa, name='lipa_na_mpesa'),
    # path('mpesa_callback/', views.mpesa_callback, name='mpesa_callback'),
    # path('send_b2c_payment/<str:phone_number>/<str:amount>/', views.send_b2c_payment, name='send_b2c_payment'),
    # path('b2c_callback/', views.b2c_callback, name='b2c_callback'),


    path('get_completed_rides/<int:rider_id>/', views.get_completed_rides, name='get_completed_rides'),
    path('check_driver_verified/<int:user_id>/', views.check_driver_verified, name='check_driver_verified'),
    path('update_rider_profile/', views.update_rider_profile, name='update_rider_profile'),
    path('get_all_drivers/', views.get_all_drivers, name='get_all_drivers'),
    path('get_all_riders/', views.get_all_riders, name='get_all_riders'),
    path('get_single_rider/<int:rider_id>/', views.get_single_rider, name='get_single_rider'),
    path('admin_rider_action/', views.admin_rider_action, name='admin_rider_action'),
    path('get_all_rides/', views.get_all_rides, name='get_all_rides'),
    path('get_all_payments/', views.get_all_payments, name='get_all_payments'),
    path('dashboard_stats/', views.dashboard_stats, name='dashboard_stats'),
    path('update_location/', views.update_location, name='update_location'),
    path('initialize_payment/', views.initialize_payment, name='initialize_payment'),
    path('confirm_ride/', views.confirm_ride, name='confirm_ride'),
    path('payment_callback/', views.payment_callback, name='payment_callback'),
    path('update_driver_status/<int:driver_id>/', views.update_driver_status, name='update_driver_status'),
    
]
