# Generated by Django 5.2.6 on 2025-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='johndoe@example.com', max_length=100),
        ),
    ]
