# Generated by Django 5.2.6 on 2025-11-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
