# Generated by Django 5.2.6 on 2025-09-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='@vincab2025', max_length=256),
        ),
    ]
