# Generated by Django 5.2.6 on 2025-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='conversation_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='originator_conversation_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='result_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='result_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
