# Generated by Django 5.2.6 on 2025-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lng',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
