# Generated by Django 5.2.6 on 2025-12-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0006_driverpayment_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('wallet', 'Wallet'), ('paystack', 'Paystack')], max_length=20),
        ),
    ]
