# Generated by Django 5.2.6 on 2025-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0007_rename_type_vehicle_vehicle_type_vehicle_current_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lng',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
