# Generated by Django 5.2.6 on 2025-09-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0008_user_current_lat_user_current_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payments', to='vincab_app.driver')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payment', to='vincab_app.payment')),
            ],
        ),
    ]
