# Generated by Django 5.2.6 on 2026-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0008_alter_user_profile_image_alter_vehicle_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/profiles/profile_HIgBKoo.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_image',
            field=models.ImageField(blank=True, default='/media/profiles/profile_HIgBKoo.jpg', null=True, upload_to='vehicles/'),
        ),
    ]
