# Generated by Django 5.2.6 on 2025-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0009_driverpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_token',
            field=models.CharField(default='hsvsx92jjs', max_length=100),
        ),
    ]
