# Generated by Django 5.2.6 on 2025-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0010_user_expo_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_lng',
        ),
    ]
