# Generated by Django 5.2.6 on 2026-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0010_alter_user_profile_image_alter_vehicle_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
