# Generated by Django 5.2.6 on 2026-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0011_alter_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('van', 'Van'), ('motorbike', 'Motorbike')], max_length=20),
        ),
    ]
