# Generated by Django 5.2.6 on 2025-11-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0012_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
