# Generated by Django 5.2.6 on 2026-02-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0012_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='vincab_app.driver'),
        ),
    ]
