# Generated by Django 5.2.6 on 2026-02-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0013_alter_rating_reviewee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpayment',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='originator_conversation_id',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='result_code',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='result_description',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionRef', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='vincab_app.driver')),
            ],
        ),
    ]
