# Generated by Django 5.2.6 on 2026-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0014_remove_driverpayment_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
