# Generated by Django 5.2.6 on 2026-02-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0015_driver_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('picked', 'Picked')], default='pending', max_length=20),
        ),
    ]
