# Generated by Django 5.2.6 on 2026-02-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0016_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updated_location',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
