# Generated by Django 5.2.6 on 2026-02-18 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0017_user_last_updated_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_updated_location',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
