# Generated by Django 5.2.6 on 2026-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0018_alter_user_last_updated_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_arrived_notified',
            field=models.BooleanField(default=False),
        ),
    ]
