# Generated by Django 5.2.6 on 2026-02-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0019_ride_driver_arrived_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='complete_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='pick_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
