# Generated by Django 5.2.6 on 2026-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0020_ride_complete_code_ride_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='float_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
