# Generated by Django 5.2.6 on 2026-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0021_driverpayment_float_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_back_image',
            field=models.ImageField(blank=True, default='/media/profiles/profile.jpg', null=True, upload_to='driver/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_front_image',
            field=models.ImageField(blank=True, default='/media/profiles/profile.jpg', null=True, upload_to='driver/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_number',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
