# Generated by Django 5.2.6 on 2026-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincab_app', '0022_driver_id_back_image_driver_id_front_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id_back_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id_front_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
    ]
